package com.ratemyrental.common.entity;

/**
 * BaseEntity Design & Architecture Documentation.
 *
 * This document explains every design decision, trade-off, and best practice.
 * Read this before extending BaseEntity or creating new entities.
 *
 * ============================================================================
 * TABLE OF CONTENTS
 * ============================================================================
 * 1. Inheritance Strategy (@MappedSuperclass)
 * 2. ID Field (BIGSERIAL)
 * 3. UUID Field (Business Identifier)
 * 4. Timestamps (createdAt, updatedAt)
 * 5. Configuration Requirements
 * 6. Guidelines for Creating Entities
 * 7. Testing Strategies
 * 8. Performance Considerations
 * 9. Security Considerations
 * 10. Future Migrations
 *
 * ============================================================================
 * 1. INHERITANCE STRATEGY: @MappedSuperclass
 * ============================================================================
 *
 * WHY @MappedSuperclass?
 * - Base fields (id, uuid, createdAt, updatedAt) are inherited by each entity
 * - No separate BaseEntity table needed
 * - Each entity table is self-contained (critical for Flyway migrations)
 * - No join overhead during queries
 * - Simple and performant
 *
 * ALTERNATIVES CONSIDERED:
 * - @Inheritance(strategy=InheritanceType.JOINED): Separate BaseEntity table
 *   ✗ Unnecessary joins on every query
 *   ✗ Complex schema with multiple tables
 *   ✗ Not needed for our use case
 *
 * - @Inheritance(strategy=InheritanceType.TABLE_PER_CLASS): All fields in each table
 *   ✗ Leads to SQL UNION queries
 *   ✗ Harder to optimize
 *   ✗ Not appropriate for independent domain entities
 *
 * - COMPOSITION (not inheritance):
 *   ✗ Extra table joins (EmbeddedId or @Embedded)
 *   ✗ More boilerplate code
 *   ✗ Harder to maintain consistency
 *
 * DECISION: @MappedSuperclass is the production-grade choice.
 *
 * ============================================================================
 * 2. ID FIELD: BIGSERIAL → Java Long
 * ============================================================================
 *
 * DATABASE SCHEMA:
 * CREATE TABLE users (
 *     id BIGSERIAL PRIMARY KEY,
 *     ...
 * );
 *
 * JAVA MAPPING:
 * @Id
 * @GeneratedValue(strategy = GenerationType.IDENTITY)
 * private Long id;
 *
 * WHY THIS APPROACH?
 * - BIGSERIAL: Auto-incrementing 64-bit integer (safe for scale)
 * - GenerationType.IDENTITY: PostgreSQL BIGSERIAL generates the value
 * - Java Long: 64-bit signed integer, can hold any BIGSERIAL value
 * - PRIMARY KEY: For efficient joins and indexing
 *
 * PERFORMANCE:
 * - Smaller than UUID (8 bytes vs 16 bytes)
 * - Faster joins in database
 * - Preferred as primary key for relational databases
 *
 * WHY NOT SEQUENCE?
 * - GenerationType.SEQUENCE with explicit sequence would also work
 * - But GenerationType.IDENTITY is simpler for existing schema
 * - No need for custom sequence if BIGSERIAL already exists
 *
 * CRITICAL: ID is INTERNAL to the system. Never expose in APIs.
 * Use UUID (business identifier) for external references instead.
 *
 * ============================================================================
 * 3. UUID FIELD: Business Identifier (Generated by Java)
 * ============================================================================
 *
 * DATABASE SCHEMA:
 * CREATE TABLE users (
 *     uuid UUID NOT NULL DEFAULT gen_random_uuid(),
 *     CONSTRAINT uq_users_uuid UNIQUE (uuid),
 *     ...
 * );
 *
 * JAVA MAPPING:
 * @GeneratedValue(strategy = GenerationType.UUID)
 * @Column(
 *     name = "uuid",
 *     columnDefinition = "UUID",
 *     nullable = false,
 *     updatable = false
 * )
 * private UUID uuid;
 *
 * WHO GENERATES UUID: JAVA, NOT POSTGRESQL
 *
 * WHY JAVA GENERATES?
 * ✓ UUID available immediately on object creation (before database insert)
 * ✓ UUID can be used in application logic without database round-trip
 * ✓ Better for batch operations and distributed systems
 * ✓ Easier to test (no DB dependency)
 * ✓ Consistent with Spring Boot 3.0+ GenerationType.UUID
 * ✓ UUID is available if transaction rolls back (can retry with same UUID)
 *
 * WHY NOT LET DATABASE GENERATE?
 * ✗ UUID only available after INSERT (requires database round-trip)
 * ✗ Cannot use UUID in application logic before commit
 * ✗ Harder to test and reason about
 * ✗ Batch inserts more complex
 *
 * EQUAL OPPORTUNITIES CLAUSE:
 * Both approaches are valid in distributed systems. We chose Java generation
 * because it's simpler and more testable.
 *
 * FUTURE MIGRATION:
 * Remove "DEFAULT gen_random_uuid()" from schema in a future migration.
 * The UUID column will still exist (data still valid), but Java will
 * generate all new UUIDs, not the database.
 *
 * EXAMPLE SQL MIGRATION:
 * ALTER TABLE users ALTER COLUMN uuid DROP DEFAULT;
 *
 * SECURITY BENEFIT:
 * UUIDs prevent ID enumeration attacks. Users cannot guess other users' IDs
 * by incrementing a number. Example API response:
 *   GET /api/users/550e8400-e29b-41d4-a716-446655440000 (safe, hard to guess)
 *   vs
 *   GET /api/users/1 (unsafe, trivial to enumerate)
 *
 * ============================================================================
 * 4. TIMESTAMPS: Instant (UTC) Managed by Spring Data JPA Auditing
 * ============================================================================
 *
 * DATABASE SCHEMA (Current):
 * created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 * updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 *
 * JAVA MAPPING:
 * @CreatedDate
 * @Column(name = "created_at", columnDefinition = "TIMESTAMP WITH TIME ZONE",
 *         nullable = false, updatable = false)
 * private Instant createdAt;
 *
 * @LastModifiedDate
 * @Column(name = "updated_at", columnDefinition = "TIMESTAMP WITH TIME ZONE",
 *         nullable = false)
 * private Instant updatedAt;
 *
 * TYPE: Instant (Not LocalDateTime)
 *
 * WHY Instant?
 * ✓ Always UTC (no timezone ambiguity)
 * ✓ ISO 8601 standard for timestamp interchange
 * ✓ Distributed systems can trust timestamps are in UTC
 * ✓ Easy to compare across regions
 * ✓ Better for auditing and compliance
 *
 * LocalDateTime Alternative?
 * ✗ No timezone info (ambiguous in multi-region systems)
 * ✗ Two different times on opposite sides of the world map to same LocalDateTime
 * ✗ Not suitable for production distributed systems
 * ✗ (It works for single-region monoliths, but doesn't scale)
 *
 * MANAGEMENT: Spring Data JPA Auditing
 *
 * HOW IT WORKS:
 * 1. @EnableJpaAuditing on @SpringBootApplication or @Configuration
 * 2. Spring Data JPA registers AuditingEntityListener
 * 3. On entity save/merge, listener intercepts persistence event
 * 4. If entity has @CreatedDate, set to now (Instant.now())
 * 5. If entity has @LastModifiedDate, update to now (Instant.now())
 * 6. Database DEFAULT serves as safety net for direct SQL
 *
 * WHY NOT DATABASE TRIGGERS?
 * ✗ Hidden logic (developers might miss it)
 * ✗ Batch operations can be affected unpredictably
 * ✗ Testing becomes harder (need full database)
 * ✗ Not portable across databases
 *
 * WHY NOT MANUAL SETTER LOGIC?
 * ✗ Error-prone (developers forget to call setter)
 * ✗ Duplicated in every entity (DRY violation)
 * ✗ Easy to introduce bugs
 *
 * CONFIGURATION REQUIRED:
 * In your @SpringBootApplication or @Configuration:
 *   @EnableJpaAuditing
 * (Already in AuditingConfiguration.java)
 *
 * DATABASE COLUMN DEFINITION:
 * ✓ columnDefinition = "TIMESTAMP WITH TIME ZONE": Explicit PostgreSQL type
 * ✓ This ensures database stores timestamps in UTC
 * ✓ Current schema uses "TIMESTAMP" (no TZ) but Java handles conversion
 *
 * FUTURE MIGRATION:
 * Update all timestamp columns to "TIMESTAMP WITH TIME ZONE":
 *   ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;
 *   ALTER TABLE users ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;
 * This makes database and Java consistent.
 *
 * ============================================================================
 * 5. CONFIGURATION REQUIREMENTS
 * ============================================================================
 *
 * FILE: application.yaml (or application.properties)
 *
 * REQUIRED:
 * spring:
 *   jpa:
 *     hibernate:
 *       ddl-auto: validate    # ← CRITICAL! NOT create or update
 *     database-platform: org.hibernate.dialect.PostgreSQLDialect
 *
 * WHY ddl-auto: validate?
 * ✓ Checks schema matches entity definitions
 * ✓ Does NOT modify the database (Flyway owns migrations)
 * ✓ Fails fast if schema is out of sync
 * ✓ Production-safe
 *
 * OPTIONAL (for development, if you want schema generation):
 * spring:
 *   config:
 *     activate:
 *       on-profile: dev
 *   jpa:
 *     hibernate:
 *       ddl-auto: update    # Only in dev profile
 *
 * CONFIGURATION ALREADY DONE:
 * - AuditingConfiguration.java: Enables @EnableJpaAuditing
 * - BaseEntity.java: Defines @CreatedDate and @LastModifiedDate
 * - No additional code needed!
 *
 * ============================================================================
 * 6. GUIDELINES FOR CREATING ENTITIES
 * ============================================================================
 *
 * TEMPLATE:
 * @Entity
 * @Table(name = "tablename")
 * public class MyEntity extends BaseEntity {
 *     private String field1;
 *     private Integer field2;
 *
 *     protected MyEntity() {
 *         super();
 *     }
 *
 *     public MyEntity(String field1, Integer field2) {
 *         super();
 *         this.field1 = field1;
 *         this.field2 = field2;
 *     }
 *
 *     public String getField1() { return field1; }
 *     public void setField1(String field1) { this.field1 = field1; }
 *
 *     public Integer getField2() { return field2; }
 *     public void setField2(Integer field2) { this.field2 = field2; }
 * }
 *
 * RULES:
 * 1. ✓ ALWAYS extend BaseEntity for aggregate roots
 * 2. ✓ ALWAYS have a protected no-arg constructor (required by JPA)
 * 3. ✓ ALWAYS have a constructor with key fields for easy instantiation
 * 4. ✓ Getters and setters for all fields
 * ✓ Use @Column for custom mapping
 * ✓ Use @ManyToOne, @OneToMany for relationships
 * ✗ DO NOT override getId() or getUuid() (inherited from BaseEntity)
 * ✗ DO NOT override getCreatedAt() or getUpdatedAt() (inherited, audited)
 * ✗ DO NOT use Lombok @Data on entities (Lombock doesn't understand JPA well)
 * ✗ DO NOT override equals() or hashCode() (inherited from BaseEntity)
 * ✗ DO NOT use mutable fields in equals() (violates JPA best practice)
 *
 * VALUE OBJECTS (Embeddables):
 * Do NOT extend BaseEntity. Use @Embeddable instead:
 *   @Embeddable
 *   public class Address {
 *       private String street;
 *       private String city;
 *   }
 *
 *   @Entity
 *   public class User extends BaseEntity {
 *       @Embedded
 *       private Address address;
 *   }
 *
 * ============================================================================
 * 7. TESTING STRATEGIES
 * ============================================================================
 *
 * UNIT TESTS (No database required):
 * - Test BaseEntity in isolation
 * - Test equals(), hashCode(), toString()
 * - Test getters/setters
 * - Test UUID generation
 * - File: BaseEntityTest.java
 *
 * INTEGRATION TESTS (With in-memory database):
 * - Test Spring Data JPA auditing (@CreatedDate, @LastModifiedDate)
 * - Test ID generation by PostgreSQL
 * - Test entity persistence and retrieval
 * - Test batch operations
 * - File: BaseEntityJpaIntegrationTest.java
 *
 * ENTITY-SPECIFIC TESTS:
 * For each entity (User, Rental, Review), write:
 * - Unit tests for business logic
 * - Integration tests for persistence
 *
 * Example:
 * @DataJpaTest
 * @Import(AuditingConfiguration.class)
 * class UserIntegrationTest {
 *     @Autowired UserRepository repository;
 *
 *     @Test
 *     void testUserIsCreatedWithAuditFields() {
 *         User user = new User("john@example.com", "password");
 *         User saved = repository.save(user);
 *
 *         assertThat(saved.getId()).isNotNull();
 *         assertThat(saved.getUuid()).isNotNull();
 *         assertThat(saved.getCreatedAt()).isNotNull();
 *         assertThat(saved.getUpdatedAt()).isNotNull();
 *     }
 * }
 *
 * ============================================================================
 * 8. PERFORMANCE CONSIDERATIONS
 * ============================================================================
 *
 * PRIMARY KEY (id: BIGSERIAL):
 * ✓ Faster joins than UUID
 * ✓ Smaller index (8 bytes vs 16 bytes)
 * ✓ Sequential allocation improves cache locality
 * ✗ Can be enumerated by attackers (mitigated by UUID)
 *
 * BUSINESS IDENTIFIER (uuid: UUID):
 * ✗ Slower joins than BIGSERIAL
 * ✓ Random distribution (no enumeration attacks)
 * ✓ Suitable for external references (APIs)
 * Strategy: Use id for internal joins, uuid for APIs
 *
 * AUDITING (createdAt, updatedAt):
 * ✓ No performance penalty (just two extra Instant values)
 * ✓ Stored as TIMESTAMP (or TIMESTAMP WITH TIME ZONE)
 * ✓ Can be indexed for time-range queries
 * ✓ Spring Data JPA auditing is negligible overhead
 *
 * BEST PRACTICE:
 * - Use id (BIGSERIAL) for all JOIN operations
 * - Use uuid (UUID) for external APIs and URLs
 * - Index created_at/updated_at if you query by time range
 *
 * ============================================================================
 * 9. SECURITY CONSIDERATIONS
 * ============================================================================
 *
 * ID ENUMERATION PREVENTION:
 * ✗ DON'T expose BIGSERIAL id in APIs:
 *    GET /api/users/1     (bad: trivial to enumerate)
 *    GET /api/users/2
 *    GET /api/users/3
 *
 * ✓ DO expose UUID in APIs:
 *    GET /api/users/550e8400-e29b-41d4-a716-446655440000  (hard to guess)
 *
 * EXAMPLE REST CONTROLLER:
 * @RestController
 * @RequestMapping("/api/users")
 * public class UserController {
 *     @GetMapping("/{uuid}")
 *     public UserDTO getUser(@PathVariable UUID uuid) {
 *         User user = userService.findByUuid(uuid);
 *         return mapper.toDTO(user);
 *     }
 * }
 *
 * AUDIT TRAIL:
 * ✓ createdAt: Immutable, useful for compliance
 * ✓ updatedAt: Useful for detecting stale caches
 * ✓ Future enhancement: Add createdBy/updatedBy fields for user tracking
 *
 * TIMESTAMP ACCURACY:
 * ✓ Instant.now() is system time (not attacker-controllable)
 * ✓ Spring Data JPA sets timestamps, not entities
 * ✓ Timestamps are stored in database (immutable once committed)
 *
 * ============================================================================
 * 10. FUTURE MIGRATIONS
 * ============================================================================
 *
 * MIGRATION 1: Remove UUID DEFAULT from database
 * File: V002__Remove_UUID_Default_From_Users.sql
 * Content:
 *     ALTER TABLE users ALTER COLUMN uuid DROP DEFAULT;
 * Reason: Java now generates UUIDs before insert
 *
 * MIGRATION 2: Add TIMESTAMP WITH TIME ZONE support
 * File: V003__Update_Timestamp_Columns_To_TZ.sql
 * Content:
 *     ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;
 *     ALTER TABLE users ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;
 * Reason: Explicit UTC support in PostgreSQL
 *
 * MIGRATION 3: Add audit user tracking (optional)
 * File: V004__Add_CreatedBy_UpdatedBy_To_Users.sql
 * Add createdBy and updatedBy columns to track which user made changes.
 * Requires:
 *   - AuditorAware<T> implementation (who is the current user?)
 *   - @CreatedBy and @LastModifiedBy annotations
 *
 * ============================================================================
 * QUICK REFERENCE
 * ============================================================================
 *
 * Annotation              Purpose                  Usage
 * ---------------------   ----------------------   --------------------------
 * @MappedSuperclass       Base entity inheritance  On BaseEntity class
 * @Id                     Primary key              On id field
 * @GeneratedValue         Auto-generation strategy On id (IDENTITY) / uuid (UUID)
 * @Column                 Column mapping           On all fields (name, nullable, etc.)
 * @CreatedDate            Auditing annotation      On createdAt field
 * @LastModifiedDate       Auditing annotation      On updatedAt field
 * @Entity                 JPA entity marker        On concrete entity classes
 * @Table                  Table name mapping       On concrete entity classes
 * @EnableJpaAuditing      Global auditing config   On @Configuration class
 *
 * ============================================================================
 * FOR MORE INFORMATION
 * ============================================================================
 *
 * See:
 * - BaseEntity.java: Full implementation with comments
 * - AuditingConfiguration.java: Auditing setup
 * - BaseEntityTest.java: Unit tests
 * - BaseEntityJpaIntegrationTest.java: Integration tests
 * - Spring Data JPA docs: https://spring.io/projects/spring-data-jpa
 * - Hibernate docs: https://hibernate.org/orm/documentation/
 * - PostgreSQL docs: https://www.postgresql.org/docs/
 */
public class BaseEntityDocumentation {
    // This is a documentation-only class. No code here.
}
