package com.ratemyrental.common.entity;

import jakarta.persistence.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;

import java.time.Instant;
import java.util.UUID;

/**
 * BaseEntity is a reusable abstract superclass for all domain entities.
 *
 * Design Decisions:
 * 1. {@code @MappedSuperclass}: Base fields are inherited by each entity table (no separate table).
 * 2. {@code id} (BIGSERIAL): Primary key for efficient joins and indexing.
 * 3. {@code uuid} (UUID): Business identifier, generated by Java, prevents ID enumeration.
 * 4. {@code Instant}: UTC timestamps for consistency across distributed systems.
 * 5. Spring Data JPA Auditing: {@code @CreatedDate} and {@code @LastModifiedDate}
 *    managed automatically, ensuring correct timestamps across all modifications.
 *
 * Database Schema:
 * - id: BIGSERIAL PRIMARY KEY (auto-incremented by PostgreSQL)
 * - uuid: UUID NOT NULL UNIQUE (generated by Java)
 * - created_at: TIMESTAMP WITH TIME ZONE NOT NULL (set once on create)
 * - updated_at: TIMESTAMP WITH TIME ZONE NOT NULL (updated on every modification)
 *
 * Usage:
 * All domain entities (User, Rental, Review, etc.) should extend this class.
 *
 * Example:
 * {@code
 * @Entity
 * @Table(name = "users")
 * public class User extends BaseEntity {
 *     private String email;
 *     private String passwordHash;
 * }
 * }
 *
 * Testing:
 * This class is NOT abstract to allow instantiation in tests.
 * However, in production code, only concrete entity classes should be persisted.
 */
@MappedSuperclass
public class BaseEntity {

    /**
     * Technical primary key: BIGSERIAL, auto-incremented by PostgreSQL.
     * Used for efficient database joins and indexing.
     * Internal to the system; never exposed in APIs.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * Business identifier: UUID, generated by Java before persistence.
     * Unique across the entire system and immutable.
     * Used for external references and API responses to prevent ID enumeration attacks.
     *
     * Generation:
     * - Strategy: GenerationType.UUID (Java generates UUID, not PostgreSQL)
     * - Availability: Immediately on entity creation, before commit
     * - Testability: Easy to mock or set in tests
     *
     * Why Java generates (not PostgreSQL):
     * - UUID available in-memory before insert (easier application logic)
     * - No database round-trip needed
     * - Better for batch operations and rollback scenarios
     * - Easier to test and reason about
     *
     * Column Definition:
     * - columnDefinition = "UUID": Explicit PostgreSQL UUID type
     * - updatable = false: UUID is immutable
     * - nullable = false: Every entity must have a UUID
     */
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(
        name = "uuid",
        columnDefinition = "UUID",
        nullable = false,
        updatable = false
    )
    private UUID uuid;

    /**
     * Creation timestamp: Set automatically by Spring Data JPA auditing.
     * Represents the exact moment the entity was first persisted.
     * Never updated after creation; immutable for audit trail purposes.
     *
     * Type: Instant
     * - Always in UTC, no timezone ambiguity
     * - Consistent with distributed system best practices
     * - ISO 8601 standard for timestamp interchange
     *
     * Management:
     * - @CreatedDate: Automatically populated by Spring Data JPA AuditingEntityListener
     * - Database DEFAULT: Serves as safety net for direct SQL inserts
     * - updatable = false: Ensures Hibernate never attempts to update this field
     *
     * Column Definition:
     * - columnDefinition = "TIMESTAMP WITH TIME ZONE": Explicit PostgreSQL type for UTC
     * - nullable = false: Every entity must have a creation timestamp
     *
     * Note: Spring Data JPA takes precedence over database DEFAULT when saving via repository.
     *
     * @see org.springframework.data.annotation.CreatedDate
     * @see org.springframework.data.jpa.domain.support.AuditingEntityListener
     */
    @CreatedDate
    @Column(
        name = "created_at",
        columnDefinition = "TIMESTAMP WITH TIME ZONE",
        nullable = false,
        updatable = false
    )
    private Instant createdAt;

    /**
     * Last modification timestamp: Updated automatically by Spring Data JPA auditing.
     * Represents the most recent moment the entity was modified.
     * Initially set to the same value as createdAt, then updated on every modification.
     *
     * Type: Instant
     * - Always in UTC
     * - Enables time-based queries (e.g., "updated in last 24 hours")
     * - Useful for optimistic locking and ETL scenarios
     *
     * Management:
     * - @LastModifiedDate: Automatically populated/updated by Spring Data JPA AuditingEntityListener
     * - Database DEFAULT + trigger: Safety net for direct SQL updates (future enhancement)
     * - nullable = false: Ensures updatedAt is always populated
     *
     * Column Definition:
     * - columnDefinition = "TIMESTAMP WITH TIME ZONE": Explicit PostgreSQL type for UTC
     * - nullable = false: Every entity must have an updated timestamp
     *
     * @see org.springframework.data.annotation.LastModifiedDate
     * @see org.springframework.data.jpa.domain.support.AuditingEntityListener
     */
    @LastModifiedDate
    @Column(
        name = "updated_at",
        columnDefinition = "TIMESTAMP WITH TIME ZONE",
        nullable = false
    )
    private Instant updatedAt;

    // ==================== Constructors ====================

    /**
     * Default constructor (required by JPA).
     * UUID and timestamps are generated/managed automatically.
     */
    protected BaseEntity() {
    }

    // ==================== Getters ====================

    /**
     * @return Technical primary key (auto-incremented by PostgreSQL).
     *         Null until entity is persisted.
     */
    public Long getId() {
        return id;
    }

    /**
     * @return Business identifier (unique UUID).
     *         Generated by Java before entity is persisted.
     */
    public UUID getUuid() {
        return uuid;
    }

    /**
     * @return Creation timestamp (immutable, in UTC).
     *         Set once when entity is first persisted.
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Last modification timestamp (in UTC).
     *         Updated automatically on every entity modification.
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    // ==================== Package-Private Setters (for auditing/testing) ====================

    /**
     * Package-private setter for testing and auditing scenarios.
     * Intentionally not public to enforce immutability in production.
     *
     * @param createdAt The creation timestamp to set (normally managed by Spring Data JPA).
     */
    protected void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Package-private setter for testing and auditing scenarios.
     * Intentionally not public to enforce immutability in production.
     *
     * @param updatedAt The last modification timestamp to set (normally managed by Spring Data JPA).
     */
    protected void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Package-private setter for UUID in tests only.
     * In production, UUID is generated automatically and immutable.
     *
     * @param uuid The UUID to set.
     */
    protected void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    // ==================== equals() & hashCode() ====================

    /**
     * Equality based on UUID (business identifier).
     *
     * Rationale:
     * - UUID is immutable and unique across the system
     * - Two entities are the same if they have the same business identity
     * - id (BIGSERIAL) is technical and may differ across replicas
     * - Never use mutable fields in equals() (this follows JPA best practice)
     *
     * Edge Case: New (unsaved) entities have UUID but no id.
     * They are compared by UUID; if both are new with same UUID, they're equal.
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;

        BaseEntity other = (BaseEntity) obj;

        // If UUID is null (should never happen with @GeneratedValue(GenerationType.UUID)),
        // fall back to identity comparison
        if (uuid == null) {
            return false;
        }

        return uuid.equals(other.uuid);
    }

    /**
     * Hash code based on UUID (business identifier).
     *
     * Rationale:
     * - Consistent with equals() implementation
     * - UUID is immutable, so hashCode is stable across entity lifecycle
     * - Safe to use in HashSet and HashMap
     *
     * Edge Case: New unsaved entities are hashable by UUID.
     */
    @Override
    public int hashCode() {
        return uuid != null ? uuid.hashCode() : 0;
    }

    // ==================== toString() ====================

    /**
     * String representation for logging and debugging.
     * Does not expose sensitive fields; includes only technical/audit info.
     *
     * Example: "User{uuid=550e8400-e29b-41d4-a716-446655440000, createdAt=2024-01-15T10:30:00Z}"
     */
    @Override
    public String toString() {
        return String.format(
            "%s{uuid=%s, createdAt=%s, updatedAt=%s}",
            getClass().getSimpleName(),
            uuid,
            createdAt,
            updatedAt
        );
    }
}
